#!/bin/sh

# kill hanged offlineimap processes
#
# adapted from
# http://pbrisbin.com/posts/mutt_gmail_offlineimap/

acct=$1

monitor() {
        local oapid=$1 i=0
        while ps $oapid &>/dev/null; do
                if (( i++ > 30 )); then
                        echo "Max checks reached for $acct. SIGKILL => ${oapid}..." >&2
                        kill -9 $oapid
                        return -42
                fi
                sleep 10
        done
        return 0
}

# offlineimap hard-codes a pid path.  arf arf!
# https://github.com/OfflineIMAP/offlineimap/blob/8c7a7355a31ce16b6d05eba6a2d0b416ff224345/offlineimap/init.py#L327

read -r pid < ~/.offlineimap/pid-$acct

if ps $pid &> /dev/null; then
        echo "Process $pid already running. Exiting..." >&2
        exit 1
else
        offlineimap -c ~/.offlineimap-$acct.rc -o &
        OAPID=$!
        echo $OAPID > ~/.offlineimap/pid-$acct
        monitor $OAPID
fi
